FROM golang:alpine@sha256:0466223b8544fb7d4ff04748acc4d75a608234bf4e79563bff208d2060c0dd79 as build

# renovate: datasource=github-releases depName=bazelbuild/buildtools
ENV BUILDIFIER_VERSION="${BUILD_VERSION:-v7.3.1}"

RUN go install github.com/bazelbuild/buildtools/buildifier@${BUILDIFIER_VERSION}

FROM owncloudci/alpine:amd64@sha256:b11caeb423b31055fcdbd4c4c0c0ae6b92e1ac50741a4f440687a5e47ec27495

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/bazel-buildifier.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/bazel-buildifier" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/bazel-buildifier"


COPY --from=build /go/bin/buildifier /usr/bin/buildifier

RUN buildifier
