FROM arm32v7/golang:alpine@sha256:b0643ee6f3ff240bd9a29e91e1be21113378b93883f7be6e554fe435617e2063 as build

RUN go install github.com/bazelbuild/buildtools/buildifier@5.1.0

FROM owncloudci/alpine:arm32v7@sha256:1e39affcacd5cb6f06e4afcc283d7ae2943e8fd2818cd26cb16f1906409fa1a1

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/bazel-buildifier.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/bazel-buildifier" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/bazel-buildifier"


COPY --from=build /go/bin/buildifier /usr/bin/buildifier

RUN buildifier
