FROM arm32v7/golang:alpine@sha256:b7a3c2dabe2e0033bf1be832c153108988ec5c45b7744d3b4619a217a3a0464a as build

# renovate: datasource=github-releases depName=bazelbuild/buildtools
ENV BUILDIFIER_VERSION="${BUILD_VERSION:-5.1.0}"

RUN go install github.com/bazelbuild/buildtools/buildifier@${BUILDIFIER_VERSION}

FROM owncloudci/alpine:arm32v7@sha256:b23884ff8b5c9951495843f6bb86117220c4d550ac26d96682df2d6b42d90318

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/bazel-buildifier.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/bazel-buildifier" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/bazel-buildifier"


COPY --from=build /go/bin/buildifier /usr/bin/buildifier

RUN buildifier
