FROM arm64v8/golang:alpine@sha256:4b693cffa390c8021b16cb1258e8d188c9782572578cb451fd037584014fa7f0 as build

# renovate: datasource=github-releases depName=bazelbuild/buildtools
ENV BUILDIFIER_VERSION="${BUILD_VERSION:-6.1.0}"

RUN go install github.com/bazelbuild/buildtools/buildifier@${BUILDIFIER_VERSION}

FROM owncloudci/alpine:arm64v8@sha256:845d0c35a4dea824ca572990816dff649781d69c9924e2b6ca13ce3c5232324d

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/bazel-buildifier.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/bazel-buildifier" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/bazel-buildifier"


COPY --from=build /go/bin/buildifier /usr/bin/buildifier

RUN buildifier
