FROM golang:alpine@sha256:08e9c086194875334d606765bd60aa064abd3c215abfbcf5737619110d48d114 as build

# renovate: datasource=github-releases depName=bazelbuild/buildtools
ENV BUILDIFIER_VERSION="${BUILD_VERSION:-6.1.0}"

RUN go install github.com/bazelbuild/buildtools/buildifier@${BUILDIFIER_VERSION}

FROM owncloudci/alpine:amd64@sha256:fc829a51989714c8ef513bc9380fd467e772dcffb80e8929d7b47b9adfd0589a

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/bazel-buildifier.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/bazel-buildifier" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/bazel-buildifier"


COPY --from=build /go/bin/buildifier /usr/bin/buildifier

RUN buildifier
