FROM arm64v8/golang:alpine@sha256:7aa06bcb60e859ace345a630c73119d3984478c0859ab261a2763795c6f945ff as build

# renovate: datasource=github-releases depName=bazelbuild/buildtools
ENV BUILDIFIER_VERSION="${BUILD_VERSION:-5.1.0}"

RUN go install github.com/bazelbuild/buildtools/buildifier@${BUILDIFIER_VERSION}

FROM owncloudci/alpine:arm64v8@sha256:d6c1acd5f39fe6183939070118ae413e275802a71ecaa5bbb98dd2b1a62e7939

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="ownCloud CI Bazel Buildifier" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/bazel-buildifier.git" \
  org.opencontainers.image.url="https://github.com/owncloud-ci/bazel-buildifier" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/bazel-buildifier"


COPY --from=build /go/bin/buildifier /usr/bin/buildifier

RUN buildifier
